cmake_minimum_required(VERSION 3.6)

set(COMMON_INC_DIR
        ${COMMON_INC_DIR})

set(FFMPEG_SOURCE_DIR ${TOPDIR}/external/ffmpeg/)

#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_TIMESPEC_DEFINED -D__SOUND_CONVERSION_SUPPORTED__")

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D__STDC_CONSTANT_MACROS -DCICADA_STATIC")
