name: iOS CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build SDK
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          . setup.env
          . build_player.sh
          build_iOS
